- id: generate-plantuml
  name: PlantUML Diagram Generator
  description: Generates images from PlantUML files and places them in the given directory.
  entry: hooks/generate_plantuml.py
  language: python
  files: (\.puml|\.pu)$