- id: generate_plantuml
  name: PlantUML Diagram Generator
  description: Generates images from PlantUML files and places them in the given directory.
  entry: generate_plantuml
  language: python
  files: (\.puml|\.pu)$