repos:
  - repo: local
    hooks:
      - id: generate-plantuml
        name: PlantUML Diagram Generator
        description: Generates images from PlantUML files and places them in the given directory.
        entry: generate-plantuml
        language: python
        additional_dependencies:
          - plantuml==0.3.0
          - six==1.16.0
        files: (\.puml|\.pu)$
        args:
          - --output-directory=@
          - --output-extension=svg
